export class Setting {
  public name: string;
  public value: string;
  public type: string;

  public static readonly KEY = {
    // Company Config
    COMPANY_REV_COMPANY_EXPENSE: "COMPANY_REV_COMPANY_EXPENSE",
    COMPANY_REV_OWNER_SHARE: "COMPANY_REV_OWNER_SHARE",
    COMPANY_REV_MODER_SHARE: "COMPANY_REV_MODER_SHARE",
    COMPANY_REV_MEMBER_SHARE: "COMPANY_REV_MEMBER_SHARE",

    // Rain Config
    POP_RAIN_BALANCE_LIMIT: "POP_RAIN_BALANCE_LIMIT",
    POP_RAIN_LAST_POST_USER: "POP_RAIN_LAST_POST_USER",

    STOCKPILE_RAIN_INTERVAL: "STOCKPILE_RAIN_INTERVAL",
    STOCKPILE_RAIN_AMOUNT: "STOCKPILE_RAIN_AMOUNT",

    RAIN_ADS_COMING_AFTER: "RAIN_ADS_COMING_AFTER",
    RAIN_ADS_DURATION: "RAIN_ADS_DURATION",
    RAIN_ADS_INTERVAL: "RAIN_ADS_INTERVAL",
    STATIC_ADS_INTERVAL: "STATIC_ADS_INTERVAL",

    COST_PER_IMPRESSION_RAIN_ADS: "COST_PER_IMPRESSION_RAIN_ADS",
    COST_PER_IMPRESSION_STATIC_ADS: "COST_PER_IMPRESSION_STATIC_ADS",

    ADS_REV_COMPANY_SHARE: "ADS_REV_COMPANY_SHARE",
    ADS_REV_IMP_REVENUE: "ADS_REV_IMP_REVENUE",

    VITAE_POST_TIME: "VITAE_POST_TIME",
    VITAE_POST_TEXT: "VITAE_POST_TEXT",

    // Membership
    MEMBERSHIP_PRICE_USD: "MEMBERSHIP_PRICE_USD",
    MEMBERSHIP_REV_COMPANY_SHARE: "MEMBERSHIP_REV_COMPANY_SHARE",
    MEMBERSHIP_REV_SPONSOR_SHARE: "MEMBERSHIP_REV_SPONSOR_SHARE",
    SPONSOR_SHARE_FIRST: "SPONSOR_SHARE_FIRST",
    SPONSOR_SHARE_SECOND: "SPONSOR_SHARE_SECOND",
    SPONSOR_SHARE_THIRD: "SPONSOR_SHARE_THIRD",

    // Expire
    TRANSACTION_REQUEST_EXPIRE: "TRANSACTION_REQUEST_EXPIRE",
    OTP_EXPIRE: "OTP_EXPIRE",
  };

  public static readonly TYPE = {
    STRING: "STRING",
    INT: "INT",
    DOUBLE: "DOUBLE",
  };
}